# Rotten Tomatoes sentiment analysis without `pipeline()`

## Learning goals

By the end of this notebook you should be able to:

* load the `cornell-movie-review-data/rotten_tomatoes` dataset
* inspect its splits and labels
* tokenize text for a Transformer model
* run a sequence-classification model directly
* postprocess logits with `softmax`
* generate predictions for many examples
* save the outputs for later use

## Important note

We are not fine-tuning in this notebook.

We are using a pretrained sentiment model and applying it to the Rotten Tomatoes dataset to see how well it transfers.

### Drive Setup

In [24]:
import os

import pandas as pd
from keras.src.metrics.accuracy_metrics import accuracy

# Change to working folder for this week:
base_path = os.getcwd()

os.chdir(base_path)

print(os.getcwd())

/Users/jacktovey/Library/CloudStorage/OneDrive-UniversityofChichester/COM407-AppliedAI/week_6

## Task 1

Import the libraries we need.

You will need:

* `datasets`
* `transformers`
* `torch`
* `pandas`

In [25]:
import datasets
import transformers
import torch
import pandas as pd
HF_TOKEN = "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"

## Task 2

Load the Rotten Tomatoes dataset from Hugging Face and store it in a variable called `ds`.

Then:

* print the split names
* print the length of each split

In [26]:
ds = datasets.load_dataset("cornell-movie-review-data/rotten_tomatoes")

In [27]:

ds.keys()

dict_keys(['train', 'validation', 'test'])

In [28]:
print(len(ds["train"]))
print(len(ds["validation"]))
print(len(ds["test"]))

8530
1066
1066

## Task 3

Inspect the structure of the dataset.

Find out:

* the column names
* the feature types
* the first training example
* the label names used by the dataset

In [29]:
print(ds["train"].column_names)
print(ds["train"].features)
print(ds["train"][0])
print(ds["train"].features["label"].names)

['text', 'label']
{'text': Value('string'), 'label': ClassLabel(names=['neg', 'pos'])}
{'text': 'the rock is destined to be the 21st century\'s new " conan " and that he\'s going to make a splash even greater than arnold schwarzenegger , jean-claud van damme or steven segal .', 'label': 1}
['neg', 'pos']

## Task 4

Take a quick look at a few examples.

Print the first 3 training reviews with:

* the raw text
* the integer label
* the label name

In [30]:
for i in range(3):
    review = ds["train"][i]
    print(f"Review {i+1}:")
    print(f"Text: {review['text']}")
    print(f"Label ID: {review['label']}")
    print(f"Label Name: {ds['train'].features['label'].names[review['label']]}")
    print("-" * 50)

Review 1:
Text: the rock is destined to be the 21st century's new " conan " and that he's going to make a splash even greater than arnold schwarzenegger , jean-claud van damme or steven segal .
Label ID: 1
Label Name: pos
--------------------------------------------------
Review 2:
Text: the gorgeously elaborate continuation of " the lord of the rings " trilogy is so huge that a column of words cannot adequately describe co-writer/director peter jackson's expanded vision of j . r . r . tolkien's middle-earth .
Label ID: 1
Label Name: pos
--------------------------------------------------
Review 3:
Text: effective but too-tepid biopic
Label ID: 1
Label Name: pos
--------------------------------------------------

## Task 5

Choose a checkpoint and load its tokenizer.

Use the checkpoint below:

`distilbert/distilbert-base-uncased-finetuned-sst-2-english`

Why this checkpoint?

* it is a very common sentiment model on Hugging Face
* it closely matches the “behind the pipeline” teaching flow
* it already has a sequence-classification head, so we can do inference immediately

In [31]:
tokenizer = transformers.AutoTokenizer.from_pretrained(
    "distilbert/distilbert-base-uncased-finetuned-sst-2-english"
)

## Task 6

Tokenize two short example sentences manually.

Use:

* one clearly positive sentence
* one clearly negative sentence

Then inspect the returned dictionary and print:

* the keys
* the tensor shapes

In [32]:
positive_sentence = "I absolutely loved this movie! It was fantastic."
negative_sentence = "I really hated this movie. It was terrible."
pos_token = tokenizer(positive_sentence, return_tensors="pt")
neg_token = tokenizer(negative_sentence, return_tensors="pt")
print(pos_token)
print(neg_token)

{'input_ids': tensor([[  101,  1045,  7078,  3866,  2023,  3185,   999,  2009,  2001, 10392,
          1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}
{'input_ids': tensor([[ 101, 1045, 2428, 6283, 2023, 3185, 1012, 2009, 2001, 6659, 1012,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

## Task 7

Load the model for sequence classification.

Then:

* move the model to thoe GPU
* switch the model to evaluation mode
* inspect `model.config.id2label`

In [33]:
model = transformers.AutoModelForSequenceClassification.from_pretrained(
    "distilbert/distilbert-base-uncased-finetuned-sst-2-english", use_safetensors=True
)
model.to("mps")
model.eval()
model.config.id2label

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

{0: 'NEGATIVE', 1: 'POSITIVE'}

## Task 8

Check where the model is stored run the following:

```python
print(next(model.parameters()).device)
```

In [34]:
print(next(model.parameters()).device)

mps:0

## Task 9

Inside `model.config` inspect both `id2label` and `label2id`.

What do you notice about how they relate to each other?

In [35]:
print(model.config.id2label)
print(model.config.label2id)

{0: 'NEGATIVE', 1: 'POSITIVE'}
{'NEGATIVE': 0, 'POSITIVE': 1}

## Task 10

Move the tokenized sample inputs onto the same device as the model.

Then run the model without using `pipeline()`.

Inspect:

* the shape of `outputs.logits`
* the raw logits

In [36]:
pos_token.to("mps")
neg_token.to("mps")

{'input_ids': tensor([[ 101, 1045, 2428, 6283, 2023, 3185, 1012, 2009, 2001, 6659, 1012,  102]],
       device='mps:0'), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], device='mps:0'), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], device='mps:0')}

In [37]:
outputpos = model(**pos_token)
outputneg = model(**neg_token)
print(outputpos.logits)
print(outputneg.logits)

tensor([[-4.3342,  4.6880]], device='mps:0', grad_fn=<LinearBackward0>)
tensor([[ 4.3190, -3.5934]], device='mps:0', grad_fn=<LinearBackward0>)

## Task 11

Convert the logits into probabilities using `softmax`.

Then:

* print the probabilities
* compute the predicted class IDs with `argmax`
* convert those IDs into label names using `id2label`

In [38]:
prob_pos = torch.softmax(outputpos.logits, dim=1)
prob_neg = torch.softmax(outputneg.logits, dim=1)
print(prob_pos)
print(prob_neg)
classid_pos = torch.argmax(outputpos.logits, dim=1)
classid_neg = torch.argmax(outputneg.logits, dim=1)
print(classid_pos)
print(classid_neg)

print(model.config.id2label[classid_pos.item()])
print(model.config.id2label[classid_neg.item()])

tensor([[1.2068e-04, 9.9988e-01]], device='mps:0', grad_fn=<SoftmaxBackward0>)
tensor([[9.9963e-01, 3.6605e-04]], device='mps:0', grad_fn=<SoftmaxBackward0>)
tensor([1], device='mps:0')
tensor([0], device='mps:0')
POSITIVE
NEGATIVE

## Task 12

When During inference we usually do not need gradients, because we are not training the model or updating weights.

Using `torch.no_grad()`:

* reduces memory usage
* can make inference faster
* avoids storing gradient information that is only needed for backpropagation (training)

The code below shows how we would run inference without the gradient calculations.

In [39]:
with torch.no_grad():
    output = model(**pos_token)

In [40]:
# encoded = {k: v.to("mps") for k, v in encoded.items()}
#
# with torch.no_grad():
#     outputs = model(**encoded)
#
# print("Logits shape:", outputs.logits.shape)
# print(outputs.logits)

## Task 13

Create a reusable preprocessing function called `tokenize_function`.

It should take a batch of examples and return tokenized outputs.

For this notebook, use:

* `truncation=True`
* `padding="max_length"`
* `max_length=128`

Why use `padding="max_length"` here?

In [41]:
def tokenize_function(examples):
    return tokenizer(
        examples["text"], truncation=True, padding="max_length", max_length=128
    )
# padding = "max_length" is used here to ensure all the reviews are of the same length as reviews longer than length are irngored and shorter need to be padded to make it the same length as the longest possible review.

## Task 14

Tokenize the data using `.map(...)`.

In [42]:
tokenized_ds = ds.map(tokenize_function, batched=True)

## Task 15

Prepare the tokenized dataset for PyTorch using only these columns:

   * `input_ids`
   * `attention_mask`
   * `label`

Hint: Use the `.set_format` attribute of the tokenised DataDict.

In [43]:
tokenized_ds.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])

## Task 16

Loop through the data and collect predictions for the whole subset.

Store:

* predicted class IDs
* confidence scores
* true labels

Hint: to convert the `logits` to probabilities use `torch.softmax('YOUR_MODEL_OUTPUT.logits, dim = -1)`. Here `dim=-1` refers aplpy softmax to each row.

In [44]:
all_preds_ids = []
all_confidences = []
all_true_ids = []

for batch in tokenized_ds['train'].iter(batch_size=128):
    inputs = {'input_ids': batch["input_ids"].to("mps"), "attention_mask": batch["attention_mask"].to("mps")}

    with torch.no_grad():
        output = model(**inputs)

    probs = torch.softmax(output.logits, dim=-1)
    preds_ids = probs.argmax(dim=-1)
    confidences = probs.max(dim=-1).values

    all_preds_ids.extend(preds_ids.tolist())
    all_confidences.extend(confidences.tolist())
    all_true_ids.extend(batch["label"].tolist())

## Task 17

Convert the integer predictions into readable label names.

Then build a pandas DataFrame containing:

* the original review text
* the true label ID
* the true label name
* the predicted label ID
* the predicted label name
* the confidence score
* whether the prediction was correct

Hint: Use the `model.config.id2label` to get the mapping of token ID to label.

In [45]:
true_label_names = [ds["train"][i]["label"] for i in range(len(ds["train"]))]
pred_label_names = [model.config.id2label[i].lower() for i in all_preds_ids]

results_df = pd.DataFrame({
    "text": ds["train"]["text"],
    "true_label_id": all_true_ids,
    "true_label": true_label_names,
    "pred_label_id": all_preds_ids,
    "pred_label": pred_label_names,
    "confidence": all_confidences,
})

results_df["correct"] = results_df["true_label_id"] == results_df["pred_label_id"]

results_df.head()

,text,true_label_id,true_label,pred_label_id,pred_label,confidence,correct
0,the rock is destined to be the 21st century's ...,1,1,1,positive,0.999836,True
1,"the gorgeously elaborate continuation of "" the...",1,1,1,positive,0.999828,True
2,effective but too-tepid biopic,1,1,0,negative,0.996004,False
3,if you sometimes like to go to the movies to h...,1,1,1,positive,0.999826,True
4,"emerges as something rare , an issue movie tha...",1,1,1,positive,0.999778,True

## Task 18

Compute the accuracy on this training data

Then count how many predictions were correct and incorrect.

In [46]:
accuracy = results_df["correct"].mean()
num_correct = results_df["correct"].sum()
num_incorrect = len(results_df) - num_correct

print(f"Accuracy: {accuracy:.4f}")
print(f"Number of correct predictions: {num_correct}")
print(f"Number of incorrect predictions: {num_incorrect}")

Accuracy: 0.8890
Number of correct predictions: 7583
Number of incorrect predictions: 947

## Task 19

Inspect some mistakes.

Show the first 10 rows where the model got the label wrong.

This is an important reminder that even a strong pretrained model can make mistakes when transferred to a different dataset.

In [48]:
mistakes_df = results_df[~results_df["correct"]]
mistakes_df.head(10)

,text,true_label_id,true_label,pred_label_id,pred_label,confidence,correct
2,effective but too-tepid biopic,1,1,0,negative,0.996004,False
7,perhaps no picture ever made has more literall...,1,1,0,negative,0.984596,False
28,"at about 95 minutes , treasure planet maintain...",1,1,0,negative,0.828581,False
33,if there's a way to effectively teach kids abo...,1,1,0,negative,0.998389,False
35,though everything might be literate and smart ...,1,1,0,negative,0.982136,False
39,"like most bond outings in recent years , some ...",1,1,0,negative,0.993932,False
43,"'compleja e intelectualmente retadora , el lad...",1,1,0,negative,0.775640,False
66,morton is a great actress portraying a complex...,1,1,0,negative,0.992480,False
77,"if this movie were a book , it would be a page...",1,1,0,negative,0.993485,False
96,"in a normal screen process , these bromides wo...",1,1,0,negative,0.818658,False

## Task 20

Save the results in two ways:

1. as a CSV file
2. as a Hugging Face Dataset saved to disk

Use the names:

* `rotten_tomatoes_manual_inference_results.csv`
* `rotten_tomatoes_manual_inference_results`

Save in the `outputs` folder for Week 6.

In [52]:
results_df.to_csv("outputs/rotten_tomatoes_manual_inference_results.csv", index=False)

results_dataset = datasets.Dataset.from_pandas(results_df)
results_dataset.save_to_disk("outputs/rotten_tomatoes_manual_inference_results", max_shard_size="100MB")

print("Results saved to disk.")

Saving the dataset (0/1 shards):   0%|          | 0/8530 [00:00<?, ? examples/s]

Results saved to disk.

## Task 21

Reload the saved Hugging Face Dataset from disk and inspect it.

This checks that your saved results can be reused later.

In [53]:
reloaded_results = datasets.load_from_disk("outputs/rotten_tomatoes_manual_inference_results")
print(reloaded_results)
print(reloaded_results[0])

Dataset({
    features: ['text', 'true_label_id', 'true_label', 'pred_label_id', 'pred_label', 'confidence', 'correct'],
    num_rows: 8530
})
{'text': 'the rock is destined to be the 21st century\'s new " conan " and that he\'s going to make a splash even greater than arnold schwarzenegger , jean-claud van damme or steven segal .', 'true_label_id': 1, 'true_label': 1, 'pred_label_id': 1, 'pred_label': 'positive', 'confidence': 0.9998360872268677, 'correct': True}