# Rotten Tomatoes sentiment analysis without `pipeline()`

## Learning goals

By the end of this notebook you should be able to:

* load the `cornell-movie-review-data/rotten_tomatoes` dataset
* inspect its splits and labels
* tokenize text for a Transformer model
* run a sequence-classification model directly
* postprocess logits with `softmax`
* generate predictions for many examples
* save the outputs for later use

## Important note

We are not fine-tuning in this notebook.

We are using a pretrained sentiment model and applying it to the Rotten Tomatoes dataset to see how well it transfers.

### Drive Setup

In [1]:
import os

# Change to working folder for this week:
base_path = os.getcwd()

os.chdir(base_path)

print(os.getcwd())

/Users/jacktovey/Library/CloudStorage/OneDrive-UniversityofChichester/COM407-AppliedAI/week_6

## Task 1

Import the libraries we need.

You will need:

* `datasets`
* `transformers`
* `torch`
* `pandas`

### Solution

In [2]:
from datasets import load_dataset, Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import pandas as pd
HF_TOKEN = "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"

## Task 2

Load the Rotten Tomatoes dataset from Hugging Face and store it in a variable called `ds`.

Then:

* print the split names
* print the length of each split

### Solution

In [3]:
ds = load_dataset("cornell-movie-review-data/rotten_tomatoes")

for split_name in ds.keys():
    print(split_name, len(ds[split_name]))

train 8530
validation 1066
test 1066

## Task 3

Inspect the structure of the dataset.

Find out:

* the column names
* the feature types
* the first training example
* the label names used by the dataset

### Solution

In [4]:
print("Columns:", ds["train"].column_names)
print("Features:", ds["train"].features)
print("\nFirst training example:")
print(ds["train"][0])

label_names = ds["train"].features["label"].names
print("\nLabel names:", label_names)

Columns: ['text', 'label']
Features: {'text': Value('string'), 'label': ClassLabel(names=['neg', 'pos'])}

First training example:
{'text': 'the rock is destined to be the 21st century\'s new " conan " and that he\'s going to make a splash even greater than arnold schwarzenegger , jean-claud van damme or steven segal .', 'label': 1}

Label names: ['neg', 'pos']

## Task 4

Take a quick look at a few examples.

Print the first 3 training reviews with:

* the raw text
* the integer label
* the label name

### Solution

In [5]:
for i in range(3):
    example = ds["train"][i]
    print(f"Example {i}")
    print("text:", example["text"])
    print("label id:", example["label"])
    print("label name:", label_names[example["label"]])
    print("-" * 80)

Example 0
text: the rock is destined to be the 21st century's new " conan " and that he's going to make a splash even greater than arnold schwarzenegger , jean-claud van damme or steven segal .
label id: 1
label name: pos
--------------------------------------------------------------------------------
Example 1
text: the gorgeously elaborate continuation of " the lord of the rings " trilogy is so huge that a column of words cannot adequately describe co-writer/director peter jackson's expanded vision of j . r . r . tolkien's middle-earth .
label id: 1
label name: pos
--------------------------------------------------------------------------------
Example 2
text: effective but too-tepid biopic
label id: 1
label name: pos
--------------------------------------------------------------------------------

## Task 5

Choose a checkpoint and load its tokenizer.

Use the checkpoint below:

`distilbert/distilbert-base-uncased-finetuned-sst-2-english`

Why this checkpoint?

* it is a very common sentiment model on Hugging Face
* it closely matches the “behind the pipeline” teaching flow
* it already has a sequence-classification head, so we can do inference immediately

### Solution

In [6]:
checkpoint = "distilbert/distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
tokenizer

BertTokenizer(name_or_path='distilbert/distilbert-base-uncased-finetuned-sst-2-english', vocab_size=30522, model_max_length=512, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
)

## Task 6

Tokenize two short example sentences manually.

Use:

* one clearly positive sentence
* one clearly negative sentence

Then inspect the returned dictionary and print:

* the keys
* the tensor shapes

### Solution

In [7]:
sample_texts = [
    "This film was funny, warm, and unexpectedly moving.",
    "This was dull, messy, and far too long."
]

encoded = tokenizer(
    sample_texts,
    padding=True,
    truncation=True,
    return_tensors="pt"
)

print(encoded.keys())
for key, value in encoded.items():
    print(key, value.shape)

encoded

KeysView({'input_ids': tensor([[  101,  2023,  2143,  2001,  6057,  1010,  4010,  1010,  1998, 14153,
          3048,  1012,   102],
        [  101,  2023,  2001, 10634,  1010, 18307,  1010,  1998,  2521,  2205,
          2146,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])})
input_ids torch.Size([2, 13])
token_type_ids torch.Size([2, 13])
attention_mask torch.Size([2, 13])

{'input_ids': tensor([[  101,  2023,  2143,  2001,  6057,  1010,  4010,  1010,  1998, 14153,
          3048,  1012,   102],
        [  101,  2023,  2001, 10634,  1010, 18307,  1010,  1998,  2521,  2205,
          2146,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

## Task 7

Load the model for sequence classification.

Then:

* move the model to thoe GPU
* switch the model to evaluation mode
* inspect `model.config.id2label`

### Solution

In [8]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint, use_safetensors=True)
model.to("mps")

print(model.config.id2label)

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

{0: 'NEGATIVE', 1: 'POSITIVE'}

## Task 8

Check where the model is stored run the following:

```python
print(next(model.parameters()).device)
```

### Solution

In [9]:
print(next(model.parameters()).device)

mps:0

## Task 9

Inside `model.config` inspect both `id2label` and `label2id`.

What do you notice about how they relate to each other?

### Solution

In [10]:
print("id2label:", model.config.id2label)
print("label2id:", model.config.label2id)

id2label: {0: 'NEGATIVE', 1: 'POSITIVE'}
label2id: {'NEGATIVE': 0, 'POSITIVE': 1}

#### Solution

`id2label` maps from integer class IDs to readable label names.

`label2id` maps from readable label names back to integer class IDs.

They are inverse mappings of each other.

## Task 10

Move the tokenized sample inputs onto the same device as the model.

Then run the model without using `pipeline()`.

Inspect:

* the shape of `outputs.logits`
* the raw logits

### Solution

In [11]:
encoded = {k: v.to("mps") for k, v in encoded.items()}


outputs = model(**encoded)

print("Logits shape:", outputs.logits.shape)
print(outputs.logits)

Logits shape: torch.Size([2, 2])
tensor([[-4.3834,  4.7097],
        [ 4.6995, -3.8391]], device='mps:0', grad_fn=<LinearBackward0>)

## Task 11

Convert the logits into probabilities using `softmax`.

Then:

* print the probabilities
* compute the predicted class IDs with `argmax`
* convert those IDs into label names using `id2label`

### Solution

In [12]:
probabilities = torch.nn.functional.softmax(outputs.logits, dim=-1)
predicted_ids = probabilities.argmax(dim=-1)

print("Probabilities:")
print(probabilities)

print("\nPredicted class IDs:")
print(predicted_ids)

predicted_labels = [model.config.id2label[i.item()] for i in predicted_ids]
print("\nPredicted labels:")
print(predicted_labels)

Probabilities:
tensor([[1.1242e-04, 9.9989e-01],
        [9.9980e-01, 1.9573e-04]], device='mps:0', grad_fn=<SoftmaxBackward0>)

Predicted class IDs:
tensor([1, 0], device='mps:0')

Predicted labels:
['POSITIVE', 'NEGATIVE']

## Task 12

When During inference we usually do not need gradients, because we are not training the model or updating weights.

Using `torch.no_grad()`:

* reduces memory usage
* can make inference faster
* avoids storing gradient information that is only needed for backpropagation (training)

The code below shows how we would run inference without the gradient calculations.

In [13]:
encoded = {k: v.to("mps") for k, v in encoded.items()}

with torch.no_grad():
    outputs = model(**encoded)

print("Logits shape:", outputs.logits.shape)
print(outputs.logits)

Logits shape: torch.Size([2, 2])
tensor([[-4.3834,  4.7097],
        [ 4.6995, -3.8391]], device='mps:0')

## Task 13

Create a reusable preprocessing function called `tokenize_function`.

It should take a batch of examples and return tokenized outputs.

For this notebook, use:

* `truncation=True`
* `padding="max_length"`
* `max_length=128`

Why use `padding="max_length"` here?

### Solution

In [14]:
def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        truncation=True,
        padding="max_length",
        max_length=128,
    )

#### Solution

We use `padding="max_length"` here to keep all tokenized reviews the same length.

This makes the notebook simpler and gives batches with a consistent shape.

In larger projects, dynamic padding is often more efficient because it avoids adding unnecessary padding tokens.

## Task 14

Tokenize the data using `.map(...)`.

### Solution

In [15]:
tokenised_ds = ds.map(tokenize_function, batched = True)

Map:   0%|          | 0/8530 [00:00<?, ? examples/s]

Map:   0%|          | 0/1066 [00:00<?, ? examples/s]

Map:   0%|          | 0/1066 [00:00<?, ? examples/s]

## Task 15

Prepare the tokenized dataset for PyTorch using only these columns:

   * `input_ids`
   * `attention_mask`
   * `label`

Hint: Use the `.set_format` attribute of the tokenised DataDict.

### Solution

In [16]:
tokenised_ds.set_format(type = 'torch', columns=["input_ids", "attention_mask", "label"])

## Task 16

Loop through the data and collect predictions for the whole subset.

Store:

* predicted class IDs
* confidence scores
* true labels

Hint: to convert the `logits` to probabilities use `torch.softmax('YOUR_MODEL_OUTPUT.logits, dim = -1)`. Here `dim=-1` refers aplpy softmax to each row.

### Solution

In [17]:
all_pred_ids = []
all_confidences = []
all_true_ids = []

for batch in tokenised_ds['train'].iter(batch_size=128):

    inputs = {'input_ids':batch["input_ids"].to("mps"), 'attention_mask' : batch["attention_mask"].to("mps")}

    with torch.no_grad():
        outputs = model(**inputs)

    probs = torch.softmax(outputs.logits, dim=-1)
    pred_ids = probs.argmax(dim=-1)
    confidences = probs.max(dim=-1).values

    all_pred_ids.extend(pred_ids.tolist())
    all_confidences.extend(confidences.tolist())
    all_true_ids.extend(batch["label"].tolist())

#### Solution

Here we loop through the dataset in batches rather than one review at a time. This is much faster and is the standard way to run inference on many examples.

Note: Before we used `model(**inputs)` to push tokens through the model. This is absolutely fine when inputs is a clean dictionary of model arguments.

However, as we have `labels` in our dataset I used the explicit form in the batched inference loop. This insures that I only pass the actual input tensors to the model.

## Task 17

Convert the integer predictions into readable label names.

Then build a pandas DataFrame containing:

* the original review text
* the true label ID
* the true label name
* the predicted label ID
* the predicted label name
* the confidence score
* whether the prediction was correct

Hint: Use the `model.config.id2label` to get the mapping of token ID to label.

### Solution

In [18]:
true_label_names = [label_names[i] for i in all_true_ids]
pred_label_names = [model.config.id2label[i].lower() for i in all_pred_ids]


results_df = pd.DataFrame({
    "text": ds['train']['text'],
    "true_label_id": all_true_ids,
    "true_label": true_label_names,
    "pred_label_id": all_pred_ids,
    "pred_label": pred_label_names,
    "confidence": all_confidences,
})

results_df["correct"] = results_df["true_label_id"] == results_df["pred_label_id"]

results_df.head()

,text,true_label_id,true_label,pred_label_id,pred_label,confidence,correct
0,the rock is destined to be the 21st century's ...,1,pos,1,positive,0.999836,True
1,"the gorgeously elaborate continuation of "" the...",1,pos,1,positive,0.999828,True
2,effective but too-tepid biopic,1,pos,0,negative,0.996004,False
3,if you sometimes like to go to the movies to h...,1,pos,1,positive,0.999826,True
4,"emerges as something rare , an issue movie tha...",1,pos,1,positive,0.999778,True

## Task 18

Compute the accuracy on this training data

Then count how many predictions were correct and incorrect.

### Solution

In [19]:
accuracy = results_df["correct"].mean()
num_correct = results_df["correct"].sum()
num_incorrect = (~results_df["correct"]).sum()

print(f"Accuracy on training examples: {accuracy:.3f}")
print("Correct:", num_correct)
print("Incorrect:", num_incorrect)

Accuracy on training examples: 0.889
Correct: 7583
Incorrect: 947

## Task 19

Inspect some mistakes.

Show the first 10 rows where the model got the label wrong.

This is an important reminder that even a strong pretrained model can make mistakes when transferred to a different dataset.

### Solution

In [20]:
mistakes = results_df[~results_df["correct"]]
mistakes.head(10)

,text,true_label_id,true_label,pred_label_id,pred_label,confidence,correct
2,effective but too-tepid biopic,1,pos,0,negative,0.996004,False
7,perhaps no picture ever made has more literall...,1,pos,0,negative,0.984596,False
28,"at about 95 minutes , treasure planet maintain...",1,pos,0,negative,0.828581,False
33,if there's a way to effectively teach kids abo...,1,pos,0,negative,0.998389,False
35,though everything might be literate and smart ...,1,pos,0,negative,0.982136,False
39,"like most bond outings in recent years , some ...",1,pos,0,negative,0.993932,False
43,"'compleja e intelectualmente retadora , el lad...",1,pos,0,negative,0.775640,False
66,morton is a great actress portraying a complex...,1,pos,0,negative,0.992480,False
77,"if this movie were a book , it would be a page...",1,pos,0,negative,0.993485,False
96,"in a normal screen process , these bromides wo...",1,pos,0,negative,0.818658,False

In [21]:
mistakes.groupby('true_label').size().sort_values(ascending=False)

true_label
neg    541
pos    406
dtype: int64

## Task 20

Save the results in two ways:

1. as a CSV file
2. as a Hugging Face Dataset saved to disk

Use the names:

* `rotten_tomatoes_manual_inference_results.csv`
* `rotten_tomatoes_manual_inference_results`

Save in the `Outputs` folder for Week 6.

### Solution

In [22]:
results_df.to_csv("outputs/rotten_tomatoes_manual_inference_results.csv", index=False)

results_dataset = Dataset.from_pandas(results_df)
results_dataset.save_to_disk("outputs/rotten_tomatoes_manual_inference_results")

print("Saved CSV and dataset directory.")

Saving the dataset (0/1 shards):   0%|          | 0/8530 [00:00<?, ? examples/s]

Saved CSV and dataset directory.

## Task 21

Reload the saved Hugging Face Dataset from disk and inspect it.

This checks that your saved results can be reused later.

### Solution

In [23]:
reloaded_results = Dataset.load_from_disk("outputs/rotten_tomatoes_manual_inference_results")
print(reloaded_results)
print(reloaded_results[0])

Dataset({
    features: ['text', 'true_label_id', 'true_label', 'pred_label_id', 'pred_label', 'confidence', 'correct'],
    num_rows: 8530
})
{'text': 'the rock is destined to be the 21st century\'s new " conan " and that he\'s going to make a splash even greater than arnold schwarzenegger , jean-claud van damme or steven segal .', 'true_label_id': 1, 'true_label': 'pos', 'pred_label_id': 1, 'pred_label': 'positive', 'confidence': 0.9998360872268677, 'correct': True}