# Week 2 — Topic Extraction + Sentiment (Multi-topic Reviews)

## Goal
You are given student reviews of a university. Each review may mention multiple topics
(e.g., Course, Library, Accommodation) and the sentiment can be mixed.

Your task:
1. Split each review into sentences
2. Predict the topic for each sentence using a Hugging Face model using the custom labels given.
3. Predict the sentiment for each sentence using a Hugging Face model
4. Aggregate results to estimate sentiment per topic per review

You will use **pipelines** (like in Week 1), but with **custom topic labels**.

### Setup Code

In [7]:

from transformers import pipeline

import pandas as pd
import numpy as np
HF_TOKEN = "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"

### Importing Data into Pandas DataFrame

Load this generated review data into a Pandas DataFrame. The url is `https://github.com/cm326/Data/raw/refs/heads/master/generated_reviews.csv` use `pd.read_csv()` to import it as a DataFrame.

In [11]:
df = pd.read_csv("/Users/jacktovey/Library/CloudStorage/OneDrive-UniversityofChichester/AppliedAI/week_2/assets/generated_reviews.csv", index_col='review_id')
df.head()

                                                 review_text
review_id
1          A couple of Computer Science units were poorly...
2          I had to chase staff a few times to get my iss...
3          The Computer Science modules were well-structu...
4          The campus facilities are modern and there are...
5          Accommodation felt secure and was decent value...

#### Solution

In [12]:
df = pd.read_csv("/Users/jacktovey/Library/CloudStorage/OneDrive-UniversityofChichester/AppliedAI/week_2/assets/generated_reviews.csv", index_col='review_id')
df.head()

                                                 review_text
review_id
1          A couple of Computer Science units were poorly...
2          I had to chase staff a few times to get my iss...
3          The Computer Science modules were well-structu...
4          The campus facilities are modern and there are...
5          Accommodation felt secure and was decent value...

### Defining the custom labels

We know that students are asked to talk about the following topics in their review.

In [13]:
TOPIC_LABELS = [
    "Course",
    "Teaching",
    "Staff",
    "Facilities",
    "Societies",
    "Library",
    "Location",
    "Accommodation",
]

Hence, these will be the custom labels we get our model to use.

### Split reviews into sentences

We are going to naively split the text on full stops (`"."`) to split the review into sentences.

This is not perfect for real-world text (e.g. abbreviations like `e.g.`),
but it is good enough for this synthetic dataset and keeps the lab simple.

To do this splitting we can take the column "review_text" and convert it to a string object using `.str()` as follows:

`df['review_text'].str()`

You can now treat it like you a manipulating a string but you are manipulating each row at the same time i.e.

`df['review_text'].str().split(".")`

This will split the string in each row individually. Now each row will be a list of the different parts that were outputted from the split.

Next you can try to tidy up the lists that we have obtained. Try this below:

Hint: You can use the `apply` function and list comphrension.

In [14]:
df["sentences"] = df["review_text"].str.split(".").apply(lambda xs: [s.strip() for s in xs if s != ""])

#### Solution

In [ ]:
df["sentences"] = df["review_text"].str.split(".").apply(lambda xs: [s.strip() for s in xs if s != ""])

Check that the sentence breakdown looks correct for a couple of examples:

In [15]:
for i in range(5):
    print(df.sentences.iloc[i])

['A couple of Computer Science units were poorly coordinated across different tutors', 'Some Computer Science modules felt outdated and there was too much overlap between units', 'There were enough online resources that I rarely needed to buy textbooks']
['I had to chase staff a few times to get my issue sorted', 'I had to chase staff a few times to get my issue sorted', 'Library staff were helpful, especially with referencing and databases']
['The Computer Science modules were well-structured and the options let me specialise in software engineering', 'Printers were often broken when lots of people needed them', 'Some key books were always checked out when deadlines approached']
['The campus facilities are modern and there are plenty of places to work between classes', 'There were enough online resources that I rarely needed to buy textbooks', 'Not all staff were consistent about deadlines and expectations', 'Some Business modules felt outdated and there was too much overlap between units', 'Some Sport Science modules felt outdated and there was too much overlap between units']
['Accommodation felt secure and was decent value for what you get', 'A couple of clubs felt cliquey and I didn’t always feel included', 'Not all staff were consistent about deadlines and expectations', 'I liked the local area and it felt safe walking back after evening sessions', 'The location was a big plus: a busy city with good transport links', 'A couple of Data Science units were poorly coordinated across different tutors']

### Creating the topic model

First create a model to us extract the topics from each sentence.

Use the `"facebook/bart-large-mnli"` model from this. Recall what type of task this is...

In [18]:
topic_classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli", device=0)

Loading weights: 100%|██████████| 515/515 [00:00<00:00, 1904.23it/s, Materializing param=model.shared.weight]

#### Solution

In [ ]:
# Topic extraction: zero-shot classification (works with our custom labels)
topic_classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli", device=0)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/515 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

### Create the Senitment Analysis model

Now create the sentiment analysis model using the default model for this task.

In [19]:
sentiment_model = pipeline("sentiment-analysis", device=0)

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.
Loading weights: 100%|██████████| 104/104 [00:00<00:00, 2046.88it/s, Materializing param=pre_classifier.weight]

#### Solution

In [ ]:
# Sentiment: (positive / negative)
sentiment_model = pipeline("sentiment-analysis",device=0)

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

### Try using the models

Now try testing the models on one sentence first to make sure everything is working as you expect.

In [20]:
topic_classifier_test = topic_classifier(df['sentences'].loc[2], TOPIC_LABELS)
topic_classifier_test

[{'sequence': 'I had to chase staff a few times to get my issue sorted',
  'labels': ['Staff',
   'Accommodation',
   'Course',
   'Facilities',
   'Library',
   'Location',
   'Societies',
   'Teaching'],
  'scores': [0.7138458490371704,
   0.06266885250806808,
   0.05332991108298302,
   0.05274029076099396,
   0.0371273048222065,
   0.036099497228860855,
   0.03388538584113121,
   0.010302860289812088]},
 {'sequence': 'I had to chase staff a few times to get my issue sorted',
  'labels': ['Staff',
   'Accommodation',
   'Course',
   'Facilities',
   'Library',
   'Location',
   'Societies',
   'Teaching'],
  'scores': [0.7138458490371704,
   0.06266885250806808,
   0.05332991108298302,
   0.05274029076099396,
   0.0371273048222065,
   0.036099497228860855,
   0.03388538584113121,
   0.010302860289812088]},
 {'sequence': 'Library staff were helpful, especially with referencing and databases',
  'labels': ['Library',
   'Staff',
   'Accommodation',
   'Location',
   'Course',
   'Societies',
   'Teaching',
   'Facilities'],
  'scores': [0.5011717677116394,
   0.31447744369506836,
   0.058239955455064774,
   0.04250778257846832,
   0.034055422991514206,
   0.018653279170393944,
   0.016620077192783356,
   0.014274198561906815]}]

#### Solution

Let's test it first.

In [ ]:
tpoic_classifier_test = topic_classifier(df['sentences'].loc[2], TOPIC_LABELS)
tpoic_classifier_test

[{'sequence': 'I had to chase staff a few times to get my issue sorted',
  'labels': ['Staff',
   'Accommodation',
   'Course',
   'Facilities',
   'Library',
   'Location',
   'Societies',
   'Teaching'],
  'scores': [0.7138455510139465,
   0.06266862154006958,
   0.05333008989691734,
   0.05274014174938202,
   0.037127409130334854,
   0.03609948232769966,
   0.033885855227708817,
   0.010302811861038208]},
 {'sequence': 'I had to chase staff a few times to get my issue sorted',
  'labels': ['Staff',
   'Accommodation',
   'Course',
   'Facilities',
   'Library',
   'Location',
   'Societies',
   'Teaching'],
  'scores': [0.7138455510139465,
   0.06266862154006958,
   0.05333008989691734,
   0.05274014174938202,
   0.037127409130334854,
   0.03609948232769966,
   0.033885855227708817,
   0.010302811861038208]},
 {'sequence': 'Library staff were helpful, especially with referencing and databases',
  'labels': ['Library',
   'Staff',
   'Accommodation',
   'Location',
   'Course',
   'Societies',
   'Teaching',
   'Facilities'],
  'scores': [0.5011729598045349,
   0.31447672843933105,
   0.05823979154229164,
   0.042507633566856384,
   0.03405541926622391,
   0.018653301522135735,
   0.016619976609945297,
   0.014274224638938904]}]

In [ ]:
sentiment_test = sentiment_model(df['sentences'].loc[2])
sentiment_test

[{'label': 'NEGATIVE', 'score': 0.9990841150283813},
 {'label': 'NEGATIVE', 'score': 0.9990841150283813},
 {'label': 'POSITIVE', 'score': 0.9981257319450378}]

In [ ]:
[x['label'] for x in sentiment_test]

['NEGATIVE', 'NEGATIVE', 'POSITIVE']

For this we would want to take the most confident prediction in each case:

So, now we can process the whole dataset but looping through

### Process the sentences

Now please process all of the sentences and put the results in a DataFrame with a row for each sentence with the sentence, label and sentiment i.e. a DataFrame with columns of 'Sentence', 'Label', 'Sentiment'.

In [22]:
all_sentences = []
for sentences in df.sentences:
    all_sentences += sentences
topic_classifier_results = topic_classifier(all_sentences, TOPIC_LABELS)
sentiment_results = sentiment_model(all_sentences)
labels = [x['labels'][0] for x in topic_classifier_results]
sentiment_labels = [y['label'] for y in sentiment_results]
df_setences = pd.DataFrame({'sentencs':all_sentences, 'Label':labels, 'Sentiment':sentiment_labels})

df_setences.head()

                                            sentencs   Label Sentiment
0  A couple of Computer Science units were poorly...  Course  NEGATIVE
1  Some Computer Science modules felt outdated an...  Course  NEGATIVE
2  There were enough online resources that I rare...   Staff  NEGATIVE
3  I had to chase staff a few times to get my iss...   Staff  NEGATIVE
4  I had to chase staff a few times to get my iss...   Staff  NEGATIVE

#### Solution

Firstly, we pull all of the sentences into one list

In [ ]:
# Let's put all the sentences into one list
all_sentences = []
for sentences in df.sentences:
    all_sentences += sentences

Now we can run these through the topic classifier with out labels

In [ ]:
# We can now process all of the sentences through the topic label model
topic_classifier_results = topic_classifier(all_sentences, TOPIC_LABELS)

We can now put these into the sentiment model to process the sentiment of each sentence

In [ ]:
# We can do the same for the sentiment model
sentiment_results = sentiment_model(all_sentences)

From here we need to pull out the most confident labels

In [ ]:
# Next we pull out the top label for each sentence
labels = [x['labels'][0] for x in topic_classifier_results]

# Quick Check
labels[:10]

['Course',
 'Course',
 'Staff',
 'Staff',
 'Staff',
 'Library',
 'Course',
 'Course',
 'Library',
 'Facilities']

Likewise we need to pull out the sentiment label

In [ ]:
# Now we can pull out the sentiment results
sentiment_labels = [y['label'] for y in sentiment_results]

# Quick Check
sentiment_labels[:10]

['NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'POSITIVE',
 'POSITIVE',
 'NEGATIVE',
 'NEGATIVE',
 'POSITIVE']

Finally, we can put this into a DataFrame to analyse

In [ ]:
df_setences = pd.DataFrame({'sentencs':all_sentences, 'Label':labels, 'Sentiment':sentiment_labels})

df_setences.head()

                                            sentencs   Label Sentiment
0  A couple of Computer Science units were poorly...  Course  NEGATIVE
1  Some Computer Science modules felt outdated an...  Course  NEGATIVE
2  There were enough online resources that I rare...   Staff  NEGATIVE
3  I had to chase staff a few times to get my iss...   Staff  NEGATIVE
4  I had to chase staff a few times to get my iss...   Staff  NEGATIVE

### Analyse the results

Explore the results to see what it tells us about sentiment for the topics. What could the uni improve based on this feedback?

In [25]:
df_setences.groupby(['Label','Sentiment']).count()
# df_setences.groupby(['Sentiment']).count()

                         sentencs
Label         Sentiment
Accommodation NEGATIVE         31
              POSITIVE         32
Course        NEGATIVE         49
              POSITIVE         33
Facilities    NEGATIVE         17
              POSITIVE         14
Library       NEGATIVE         18
              POSITIVE         10
Location      NEGATIVE         37
              POSITIVE         22
Societies     NEGATIVE          4
              POSITIVE         18
Staff         NEGATIVE         44
              POSITIVE         19
Teaching      POSITIVE          7

#### Solution

We can use the `groupby` functionn in Pandas to group by 'Label' and 'Sentiment'. Once we group like this we can use `.count()` to count the sizes of the groups.

In [ ]:
df_setences.groupby(['Label','Sentiment']).count()

                         sentencs
Label         Sentiment
Accommodation NEGATIVE         31
              POSITIVE         32
Course        NEGATIVE         49
              POSITIVE         33
Facilities    NEGATIVE         17
              POSITIVE         14
Library       NEGATIVE         18
              POSITIVE         10
Location      NEGATIVE         37
              POSITIVE         22
Societies     NEGATIVE          4
              POSITIVE         18
Staff         NEGATIVE         44
              POSITIVE         19
Teaching      POSITIVE          7

Unfortunately, most of the feedback is negative.

In [ ]:
df_setences.groupby(['Sentiment']).count()

           sentencs  Label
Sentiment
NEGATIVE        200    200
POSITIVE        155    155